# Generated by Django 4.2.7 on 2025-10-20 11:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=50, unique=True, verbose_name='payment ID')),
                ('transaction_reference', models.CharField(blank=True, max_length=200, verbose_name='transaction reference')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('processing_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='processing fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='net amount')),
                ('payment_trigger', models.CharField(choices=[('job_completion', 'Job Completion'), ('milestone_completion', 'Milestone Completion'), ('scheduled', 'Scheduled Payment'), ('manual', 'Manual Payment'), ('dispute_resolution', 'Dispute Resolution')], max_length=20, verbose_name='payment trigger')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='scheduled date')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='processed date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='status')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('retry_count', models.IntegerField(default=0, verbose_name='retry count')),
                ('max_retries', models.IntegerField(default=3, verbose_name='max retries')),
                ('bank_account_number', models.CharField(blank=True, max_length=100, verbose_name='bank account number')),
                ('bank_routing_number', models.CharField(blank=True, max_length=50, verbose_name='bank routing number')),
                ('bank_name', models.CharField(blank=True, max_length=200, verbose_name='bank name')),
                ('account_holder_name', models.CharField(blank=True, max_length=200, verbose_name='account holder name')),
                ('wallet_address', models.CharField(blank=True, max_length=100, verbose_name='wallet address')),
                ('crypto_currency', models.CharField(blank=True, max_length=20, verbose_name='crypto currency')),
                ('blockchain_network', models.CharField(blank=True, max_length=50, verbose_name='blockchain network')),
                ('processor_transaction_id', models.CharField(blank=True, max_length=200, verbose_name='processor transaction ID')),
                ('processor_response', models.JSONField(default=dict, verbose_name='processor response')),
                ('smart_contract_address', models.CharField(blank=True, max_length=42, verbose_name='smart contract address')),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=66, verbose_name='blockchain transaction hash')),
                ('gas_fee', models.DecimalField(decimal_places=8, default=0, max_digits=10, verbose_name='gas fee')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Contractor Payment',
                'verbose_name_plural': 'Contractor Payments',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('dispute_type', models.CharField(choices=[('payment_quality', 'Payment vs Quality'), ('payment_timing', 'Payment Timing'), ('payment_amount', 'Payment Amount'), ('cancelled_job', 'Cancelled Job'), ('other', 'Other')], max_length=30, verbose_name='dispute type')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('closed', 'Closed')], default='submitted', max_length=20, verbose_name='status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('resolution_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='resolution amount')),
                ('resolution_type', models.CharField(blank=True, max_length=50, verbose_name='resolution type')),
            ],
            options={
                'verbose_name': 'Dispute Resolution',
                'verbose_name_plural': 'Dispute Resolutions',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='EscrowAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('escrow_id', models.CharField(max_length=50, unique=True, verbose_name='escrow ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='total amount')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='platform fee')),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='net amount for freelancer')),
                ('status', models.CharField(choices=[('active', 'Active'), ('pending_deposit', 'Pending Deposit'), ('funded', 'Funded'), ('released', 'Released'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled')], default='pending_deposit', max_length=20, verbose_name='status')),
                ('funded_date', models.DateTimeField(blank=True, null=True, verbose_name='funded date')),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='release date')),
                ('release_trigger', models.CharField(blank=True, max_length=50, verbose_name='release trigger')),
                ('smart_contract_address', models.CharField(blank=True, max_length=42, verbose_name='smart contract address')),
                ('blockchain_transaction_hash', models.CharField(blank=True, max_length=66, verbose_name='blockchain transaction hash')),
                ('contract_deployed_at', models.DateTimeField(blank=True, null=True, verbose_name='contract deployed at')),
                ('escrow_provider', models.CharField(blank=True, max_length=100, verbose_name='escrow provider')),
                ('escrow_account_number', models.CharField(blank=True, max_length=100, verbose_name='escrow account number')),
                ('dispute_reason', models.TextField(blank=True, verbose_name='dispute reason')),
                ('dispute_raised_at', models.DateTimeField(blank=True, null=True, verbose_name='dispute raised at')),
                ('auto_release_hours', models.IntegerField(default=72, verbose_name='auto release hours')),
                ('requires_client_approval', models.BooleanField(default=True, verbose_name='requires client approval')),
                ('requires_freelancer_confirmation', models.BooleanField(default=False, verbose_name='requires freelancer confirmation')),
            ],
            options={
                'verbose_name': 'Escrow Account',
                'verbose_name_plural': 'Escrow Accounts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='payment method name')),
                ('payment_type', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('crypto_wallet', 'Crypto Wallet'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('escrow_crypto', 'Escrow Crypto'), ('escrow_traditional', 'Escrow Traditional')], max_length=30, verbose_name='payment type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('processing_fee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='processing fee percentage')),
                ('min_payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='min payment amount')),
                ('max_payment_amount', models.DecimalField(decimal_places=2, default=999999999.99, max_digits=15, verbose_name='max payment amount')),
                ('supported_currencies', models.JSONField(default=list, verbose_name='supported currencies')),
                ('requires_kyc', models.BooleanField(default=False, verbose_name='requires KYC')),
                ('settlement_time_hours', models.IntegerField(default=24, verbose_name='settlement time hours')),
                ('web3_enabled', models.BooleanField(default=False, verbose_name='Web3 enabled')),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('schedule_type', models.CharField(choices=[('weekly', 'Weekly'), ('bi_weekly', 'Bi-weekly'), ('monthly', 'Monthly'), ('per_job', 'Per Job'), ('milestone_based', 'Milestone Based')], max_length=20, verbose_name='schedule type')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('next_payment_date', models.DateTimeField(verbose_name='next payment date')),
                ('fixed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='fixed amount')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='currency')),
                ('accumulated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='accumulated amount')),
            ],
            options={
                'verbose_name': 'Payment Schedule',
                'verbose_name_plural': 'Payment Schedules',
                'ordering': ['next_payment_date'],
            },
        ),
    ]
