# Generated by Django 4.2.7 on 2025-10-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractor_payments', '0001_initial'),
        ('freelancers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gig_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedules', to='freelancers.freelancer'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='contractor_payments.paymentmethod'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='dispute_raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raised_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_accounts', to='freelancers.freelancer'),
        ),
        migrations.AddField(
            model_name='escrowaccount',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escrow_accounts', to='gig_management.gigjob'),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='escrow_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contractor_payments.escrowaccount'),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='contractor_payments.contractorpayment'),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='raised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='disputeresolution',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_disputes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorpayment',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorpayment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorpayment',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='freelancers.freelancer'),
        ),
        migrations.AddField(
            model_name='contractorpayment',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gig_management.gigjob'),
        ),
        migrations.AddField(
            model_name='contractorpayment',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='gig_management.jobmilestone'),
        ),
        migrations.AddField(
            model_name='contractorpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='contractor_payments.paymentmethod'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['escrow_id'], name='contractor__escrow__042dfa_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['status', 'created'], name='contractor__status_8c2ace_idx'),
        ),
        migrations.AddIndex(
            model_name='escrowaccount',
            index=models.Index(fields=['job', 'status'], name='contractor__job_id_96ee8e_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['payment_id'], name='contractor__payment_3c8f15_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['freelancer', 'status'], name='contractor__freelan_b6d6b3_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['status', 'scheduled_date'], name='contractor__status_d3c107_idx'),
        ),
        migrations.AddIndex(
            model_name='contractorpayment',
            index=models.Index(fields=['created'], name='contractor__created_228aba_idx'),
        ),
    ]
