[project]
name = "tidygen-py-sdk"
version = "0.1.0"
description = "Minimal Python SDK for interacting with TidyGen ink! contract"
authors = [
  { name="TidyGen Community", email="team@tidygen-erp.com" }
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"