# Generated by Django 4.2.7 on 2025-09-19 15:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dashboard',
            options={'ordering': ['-created'], 'verbose_name': 'Dashboard', 'verbose_name_plural': 'Dashboards'},
        ),
        migrations.AlterModelOptions(
            name='datasource',
            options={'ordering': ['-created'], 'verbose_name': 'Data Source', 'verbose_name_plural': 'Data Sources'},
        ),
        migrations.AlterModelOptions(
            name='kpi',
            options={'ordering': ['-created'], 'verbose_name': 'KPI', 'verbose_name_plural': 'KPIs'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
        migrations.AlterModelOptions(
            name='reporttemplate',
            options={'ordering': ['-created'], 'verbose_name': 'Report Template', 'verbose_name_plural': 'Report Templates'},
        ),
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.organization'),
            preserve_default=False,
        ),
    ]
