# Generated by Django 4.2.7 on 2025-10-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_templates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='kpimeasurement',
            name='kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='analytics.kpi'),
        ),
        migrations.AddField(
            model_name='datasource',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='core.organization'),
        ),
        migrations.AddField(
            model_name='dashboardwidget',
            name='dashboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.dashboard'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='accessible_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_dashboards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.organization'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='core.organization'),
        ),
        migrations.AddField(
            model_name='analyticsevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='related_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='analytics.dashboard'),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='related_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='analytics.kpi'),
        ),
        migrations.AddField(
            model_name='analyticscache',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cache_entries', to='analytics.report'),
        ),
        migrations.AddField(
            model_name='alert',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.organization'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_dashboard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='analytics.dashboard'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_kpi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='analytics.kpi'),
        ),
        migrations.AddField(
            model_name='alert',
            name='related_report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='analytics.report'),
        ),
        migrations.AlterUniqueTogether(
            name='kpimeasurement',
            unique_together={('kpi', 'measurement_date')},
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_type', 'event_timestamp'], name='analytics_a_event_t_0a174a_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['user', 'event_timestamp'], name='analytics_a_user_id_4a5f7d_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsevent',
            index=models.Index(fields=['event_timestamp'], name='analytics_a_event_t_767ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['cache_key'], name='analytics_a_cache_k_9a5fb4_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['expires_at'], name='analytics_a_expires_4e35a3_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticscache',
            index=models.Index(fields=['cache_type'], name='analytics_a_cache_t_78d0e5_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status', 'severity'], name='analytics_a_status_361499_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['alert_type', 'triggered_at'], name='analytics_a_alert_t_0878b3_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['status'], name='analytics_a_status_3e9fdc_idx'),
        ),
    ]
