# Generated by Django 4.2.7 on 2025-09-19 15:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('analytics', '0002_alter_dashboard_options_alter_datasource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='core.organization'),
            preserve_default=False,
        ),
    ]
