# Generated by Django 4.2.7 on 2025-09-19 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_dashboard_options_alter_datasource_options_and_more'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.organization'),
            preserve_default=False,
        ),
    ]
