# Generated by Django 4.2.7 on 2025-09-19 15:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('analytics', '0004_datasource_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analytics_events', to='core.organization'),
            preserve_default=False,
        ),
    ]
