# Generated by Django 4.2.7 on 2025-10-20 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('audit_trail', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who triggered the event', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['event_type', 'timestamp'], name='audit_trail_event_t_b6b1af_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['module', 'timestamp'], name='audit_trail_module_23f58b_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['user', 'timestamp'], name='audit_trail_user_id_5e712a_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['status', 'timestamp'], name='audit_trail_status_ff87e1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['on_chain_tx_hash'], name='audit_trail_on_chai_e05b95_idx'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['ipfs_hash'], name='audit_trail_ipfs_ha_dd7300_idx'),
        ),
    ]
